version: "3.7"

services:
  database_anime:
    image: postgres
    container_name: database_anime
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=dev
      - POSTGRES_PASSWORD=Luis9090
      - POSTGRES_DB=animes
    volumes:
      - mydata:/data/mysql

volumes:
  mydata:
    driver: local