version: "3.7"

services:
  database_anime:
    image: postgres
    container_name: database_anime
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=luisnunes
      - POSTGRES_PASSWORD=user123
      - POSTGRES_DB=animesv3
    volumes:
      - mydata:/data/mysql

volumes:
  mydata:
    driver: local